channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - ld_impl_linux-64=2.40
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libnsl=2.0.1
  - libsqlite=3.45.2
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - ncurses=6.4.20240210
  - openssl=3.2.1
  - pip=24.0
  - python=3.11.8
  - pytz=2024.1
  - readline=8.2
  - setuptools=69.2.0
  - tk=8.6.13
  - wheel=0.43.0
  - xz=5.2.6
  - pip:
      - annotated-types==0.6.0
      - beautifulsoup4==4.12.3
      - certifi==2024.2.2
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - et-xmlfile==1.1.0
      - idna==3.6
      - numpy==1.26.4
      - openpyxl==3.1.2
      - pandas==2.2.1
      - pillow==10.3.0
      - pyarrow==15.0.2
      - pydantic==2.6.4
      - pydantic-core==2.16.3
      - python-dateutil==2.9.0.post0
      - reportlab==4.1.0
      - requests==2.31.0
      - six==1.16.0
      - soupsieve==2.5
      - typing-extensions==4.10.0
      - tzdata==2024.1
      - urllib3==2.2.1
