from .website import WebSite
from .canaltech import CanalTech
from .gizmodo import GizModo
from .globo import Globo
from .olhardigital import OlharDigital
from .tabnews import TabNews
from .techcrunch import TechCrunch
from .techtudo import TechTudo
from .thenextweb import TheNextWeb
